# Generated by Django 3.2.2 on 2021-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=20, unique=True, verbose_name='使用者ID')),
                ('UserName', models.CharField(max_length=20, unique=True, verbose_name='使用者名稱')),
                ('UserAccount', models.CharField(max_length=20, unique=True, verbose_name='使用者帳號')),
                ('UserPassword', models.CharField(max_length=20, unique=True, verbose_name='使用者密碼')),
                ('Email', models.CharField(max_length=20, unique=True, verbose_name='使用者電子郵件')),
            ],
            options={
                'verbose_name': '會員管理',
                'verbose_name_plural': '會員管理',
            },
        ),
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Pet',
        ),
    ]
