# Generated by Django 3.2.3 on 2021-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20210507_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(max_length=30, verbose_name='項目')),
                ('kind', models.IntegerField(default=0, verbose_name='類別')),
                ('price', models.IntegerField(default=0, verbose_name='金額')),
            ],
            options={
                'verbose_name': '記帳',
                'verbose_name_plural': '記帳',
            },
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': '寵物', 'verbose_name_plural': '寵物'},
        ),
    ]
