# Generated by Django 3.2.3 on 2021-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20210529_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='money',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='origin_place',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='roast',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='tags',
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Bulldog', '鬥牛犬'), ('Corgi', '柯基'), ('Chihuahua', '吉娃娃'), ('Dachshund', '臘腸狗'), ('Golden', '黃金獵犬'), ('Labrador', '拉布拉多'), ('Maltese', '馬爾濟斯'), ('Pomeranian', '博美'), ('Poodle', '貴賓犬'), ('Husky', '哈士奇'), ('Terrier', '約克夏'), ('Schnauzer', '雪納瑞')], default='請選擇', max_length=10, verbose_name='品種'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(verbose_name='特徵'),
        ),
        migrations.DeleteModel(
            name='OriginPlace',
        ),
    ]
