# Generated by Django 3.2.4 on 2021-06-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20210604_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
