# Generated by Django 3.2.4 on 2021-06-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20210611_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='check_password',
            field=models.CharField(default='請再輸入一次密碼', max_length=15),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', '公'), ('female', '母')], default='請選擇', max_length=10, verbose_name='性別'),
        ),
    ]
