# Generated by Django 3.2.4 on 2021-06-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20210611_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': '註冊', 'verbose_name_plural': '註冊'},
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='user_pwd',
        ),
    ]
