# Generated by Django 3.2.4 on 2021-06-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20210611_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='userID',
            new_name='username',
        ),
    ]
