# Generated by Django 3.2.4 on 2021-07-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_rename_userid_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='check_password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
