# Generated by Django 3.2.4 on 2021-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_alter_register_check_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='時間'),
        ),
    ]
