# Generated by Django 3.2.4 on 2021-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_money_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='category',
            field=models.CharField(choices=[('food', '食物'), ('toy', '玩具'), ('clothes', '衣服'), ('salon', '美容'), ('others', '其他')], default='未分類', max_length=255),
        ),
        migrations.AlterField(
            model_name='money',
            name='item',
            field=models.CharField(max_length=255, verbose_name='項目'),
        ),
    ]
