# Generated by Django 3.2.4 on 2021-07-22 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_alter_money_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='category',
            field=models.CharField(choices=[('food', '食物'), ('toy', '玩具'), ('clothes', '衣服'), ('salon', '美容'), ('others', '其他')], default='未分類', max_length=255),
        ),
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 11, 26, 37, 971113, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='register',
            name='check_password',
            field=models.CharField(default='請再輸入一次密碼', max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.CharField(default='請輸入你的電子郵件', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_pwd',
            field=models.CharField(default='請輸入你的密碼', max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(default='請輸入你的帳號', max_length=15),
        ),
    ]
