# Generated by Django 3.2.6 on 2021-08-05 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_auto_20210722_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 15, 0, 44, 691143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='register',
            name='check_password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_pwd',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
