# Generated by Django 3.2.6 on 2021-08-05 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_alter_money_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
