# Generated by Django 3.2.4 on 2021-10-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_auto_20210801_2043'),
        ('pets', '0020_alter_money_time'),
    ]

    operations = [
    ]
