# Generated by Django 3.2.4 on 2021-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_auto_20211015_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(verbose_name='時間'),
        ),
    ]
