# Generated by Django 3.2.4 on 2021-11-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_auto_20211015_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='標題'),
        ),
    ]
