# Generated by Django 3.2.4 on 2021-10-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_alter_money_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='price',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default='請選擇時間'),
        ),
    ]
