# Generated by Django 3.2.4 on 2021-10-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_auto_20211021_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='category',
            field=models.CharField(choices=[('food', '食物'), ('toy', '玩具'), ('clothes', '衣服'), ('salon', '美容'), ('others', '其他')], max_length=255, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='money',
            name='item',
            field=models.CharField(choices=[("{'飼料', '餅乾', '鮮食', '潔牙骨', '肉乾'}", 'Food'), ("{'繩索', '玩偶', '球', '塑膠玩具', '飛盤'}", 'Toy'), ("{'褲裝', '領巾', '裙裝'}", 'Clothes'), ("{'洗澡', '剪毛'}", 'Salon'), ("{'項圈', '預防針', '看醫生', '保養品'}", 'Others')], max_length=255, verbose_name='項目'),
        ),
    ]
