# Generated by Django 3.2.3 on 2021-11-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_alter_event_title'),
        ('pets', '0026_auto_20211102_2127'),
    ]

    operations = [
    ]
