# Generated by Django 3.2.9 on 2021-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0027_merge_0023_alter_event_title_0026_auto_20211102_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default='請選擇時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default='請選擇時間'),
        ),
        migrations.AlterField(
            model_name='money',
            name='category',
            field=models.CharField(choices=[('food', '食物'), ('toy', '玩具'), ('clothes', '衣服'), ('salon', '美容'), ('others', '其他')], max_length=255, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='money',
            name='item',
            field=models.CharField(choices=[('food', '肉乾'), ('food1', '鮮食'), ('toy', '飛盤'), ('clothes', '領巾'), ('salon', '剪毛'), ('others', '項圈')], max_length=255, verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.EmailField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
