# Generated by Django 3.2.9 on 2021-11-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0028_auto_20211118_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateField(default='請選擇時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateField(default='請選擇時間'),
        ),
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateField(default='請選擇時間'),
        ),
    ]
