# Generated by Django 3.2.9 on 2021-11-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0029_auto_20211123_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Money',
            new_name='Bookkeeping',
        ),
    ]
