# Generated by Django 3.2.4 on 2021-11-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0029_auto_20211123_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default='請選擇時間'),
        ),
    ]
