# Generated by Django 3.2.4 on 2021-11-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0030_alter_money_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateField(default='請選擇時間'),
        ),
    ]
