# Generated by Django 3.2.9 on 2021-11-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0031_rename_bookkeeping_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default='請選擇時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default='請選擇時間'),
        ),
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default='請選擇時間'),
        ),
    ]
