# Generated by Django 3.2.9 on 2021-11-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0033_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.register'),
        ),
    ]
