# Generated by Django 3.2.9 on 2021-11-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0034_auto_20211128_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='username',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='pets.register'),
        ),
    ]
