# Generated by Django 3.2.9 on 2021-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0035_money_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='username',
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
