# Generated by Django 3.2.9 on 2021-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0037_alter_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='item',
            field=models.CharField(choices=[('<django.db.models.fields.related.ForeignKey>', 'Food'), ('toy', '飛盤'), ('clothes', '領巾'), ('salon', '剪毛'), ('others', '項圈')], max_length=255, verbose_name='項目'),
        ),
    ]
