# Generated by Django 3.2.9 on 2021-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0038_alter_money_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='username',
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
