# Generated by Django 3.2.9 on 2021-11-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0036_auto_20211128_2058'),
        ('pets', '0040_alter_login_username'),
    ]

    operations = [
    ]
