# Generated by Django 3.2.9 on 2021-11-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0041_merge_20211128_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='username_id',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='username_id',
        ),
        migrations.AlterField(
            model_name='money',
            name='item',
            field=models.CharField(choices=[('food', '食物'), ('toy', '飛盤'), ('clothes', '領巾'), ('salon', '剪毛'), ('others', '項圈')], max_length=255, verbose_name='項目'),
        ),
    ]
