# Generated by Django 3.2.9 on 2021-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0042_auto_20211128_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username_id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='money',
            name='item',
            field=models.CharField(choices=[('food', '肉乾'), ('food1', '鮮食'), ('toy', '飛盤'), ('clothes', '領巾'), ('salon', '剪毛'), ('others', '項圈')], max_length=255, verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.CharField(max_length=20),
        ),
    ]
