# Generated by Django 3.2.9 on 2021-11-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0044_alter_login_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='pets_login',
        ),
        migrations.AlterModelTable(
            name='register',
            table='pets_register',
        ),
    ]
