# Generated by Django 3.2.9 on 2021-11-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0045_auto_20211128_2331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table=None,
        ),
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
