# Generated by Django 3.2.9 on 2021-11-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0049_auto_20211130_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_title',
            field=models.CharField(max_length=255, verbose_name='標題'),
        ),
    ]
