# Generated by Django 3.2.9 on 2021-11-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0050_alter_shop_shop_title'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='login',
        #     name='username',
        # ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=15)
        ),
    ]
