# Generated by Django 3.2.9 on 2021-11-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0050_alter_shop_shop_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
