# Generated by Django 3.2.9 on 2021-11-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0051_alter_login_username'),
        ('pets', '0051_auto_20211130_1325'),
    ]

    operations = [
    ]
