# Generated by Django 3.2.9 on 2021-12-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0031_alter_money_time'),
        ('pets', '0052_merge_20211130_1424'),
    ]

    operations = [
    ]
