# Generated by Django 3.2.9 on 2021-12-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0053_merge_0031_alter_money_time_0052_merge_20211130_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', '食物'), ('toy', '玩具'), ('clothes', '衣服'), ('salon', '美容'), ('others', '其他')], max_length=255, verbose_name='類別')),
                ('item', models.CharField(choices=[('肉乾', '肉乾'), ('鮮食', '鮮食'), ('飛盤', '飛盤'), ('clothes', '領巾'), ('salon', '剪毛'), ('others', '項圈')], max_length=255, verbose_name='項目')),
            ],
        ),
        migrations.AlterField(
            model_name='money',
            name='item',
            field=models.CharField(choices=[('肉乾', '肉乾'), ('鮮食', '鮮食'), ('飛盤', '飛盤'), ('clothes', '領巾'), ('salon', '剪毛'), ('others', '項圈')], max_length=255, verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default='請選擇時間'),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
