# Generated by Django 3.2.9 on 2021-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0054_auto_20211202_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
