# Generated by Django 3.2.9 on 2021-12-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0056_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.CharField(max_length=20),
        ),
    ]
