# Generated by Django 3.2.9 on 2021-12-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0057_alter_register_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='time',
            new_name='data_time',
        ),
    ]
