# Generated by Django 3.2.9 on 2021-12-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0058_rename_time_money_data_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='data_time',
            new_name='time',
        ),
    ]
