# Generated by Django 3.2.9 on 2021-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0060_alter_money_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='produce_url',
            field=models.CharField(default='', max_length=255, verbose_name='產品網址'),
        ),
    ]
