# Generated by Django 3.2.9 on 2021-12-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0054_auto_20211202_1357'),
        ('pets', '0062_auto_20211205_1703'),
    ]

    operations = [
    ]
