# Generated by Django 3.2.9 on 2021-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0063_merge_0054_auto_20211202_1357_0062_auto_20211205_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_url', models.CharField(default='', max_length=255, verbose_name='圖片網址')),
                ('clothes_produce_url', models.CharField(default='', max_length=255, verbose_name='產品網址')),
                ('clothes_title', models.CharField(max_length=255, verbose_name='標題')),
                ('clothes_price', models.CharField(max_length=20, verbose_name='價格')),
            ],
            options={
                'verbose_name': '衣服',
                'verbose_name_plural': '衣服',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.CharField(default='', max_length=255, verbose_name='圖片網址')),
                ('feed_produce_url', models.CharField(default='', max_length=255, verbose_name='產品網址')),
                ('feed_title', models.CharField(max_length=255, verbose_name='標題')),
                ('feed_price', models.CharField(max_length=20, verbose_name='價格')),
            ],
            options={
                'verbose_name': '飼料',
                'verbose_name_plural': '飼料',
            },
        ),
        migrations.CreateModel(
            name='Fresh_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fresh_food', models.CharField(default='', max_length=255, verbose_name='圖片網址')),
                ('Fresh_food_produce_url', models.CharField(default='', max_length=255, verbose_name='產品網址')),
                ('Fresh_food_title', models.CharField(max_length=255, verbose_name='標題')),
                ('Fresh_food_price', models.CharField(max_length=20, verbose_name='價格')),
            ],
            options={
                'verbose_name': '鮮食',
                'verbose_name_plural': '鮮食',
            },
        ),
        migrations.DeleteModel(
            name='Mobject',
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '配件', 'verbose_name_plural': '配件'},
        ),
        migrations.AlterField(
            model_name='money',
            name='item',
            field=models.CharField(choices=[('肉乾', '肉乾'), ('鮮食', '鮮食'), ('飼料', '飼料'), ('餅乾', '餅乾'), ('潔牙骨', '潔牙骨'), ('飛盤', '飛盤'), ('球', '球'), ('繩索', '繩索'), ('玩偶', '玩偶'), ('塑膠玩具', '塑膠玩具'), ('領巾', '領巾'), ('褲裝', '褲裝'), ('裙裝', '裙裝'), ('洗澡', '洗澡'), ('剪毛', '剪毛'), ('預防針', '預防針'), ('保養品', '保養品'), ('看醫生', '看醫生'), ('項圈', '項圈')], max_length=255, verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.CharField(default='請選擇時間', max_length=255),
        ),
    ]
